export default [
  { id: "1", name: "Bachelor of Applied Science (B.A.Sc.)" },
  { id: "2", name: "Bachelor of Arts (BA) in Anthropology" },
  { id: "3", name: "Bachelor of Arts (BA) in Archaeology" },
  { id: "4", name: "Bachelor of Arts (BA) in Art History" },
  { id: "5", name: "Bachelor of Arts (BA) in Classics" },
  { id: "6", name: "Bachelor of Arts (BA) in Creative Writing" },
  { id: "7", name: "Bachelor of Arts (BA) in Cultural Studies" },
  { id: "8", name: "Bachelor of Arts (BA) in English" },
  { id: "9", name: "Bachelor of Arts (BA) in Film Studies" },
  { id: "10", name: "Bachelor of Arts (BA) in Gender Studies" },
  { id: "11", name: "Bachelor of Arts (BA) in History" },
  { id: "12", name: "Bachelor of Arts (BA) in International Studies" },
  { id: "13", name: "Bachelor of Arts (BA) in Language and Literature" },
  { id: "14", name: "Bachelor of Arts (BA) in Music" },
  { id: "15", name: "Bachelor of Arts (BA) in Philosophy" },
  { id: "16", name: "Bachelor of Arts (BA) in Political Science" },
  { id: "17", name: "Bachelor of Arts (BA) in Psychology" },
  { id: "18", name: "Bachelor of Arts (BA) in Religious Studies" },
  { id: "19", name: "Bachelor of Arts (BA) in Sociology" },
  { id: "20", name: "Bachelor of Arts (BA) in Theatre" },
  { id: "21", name: "Bachelor of Arts (BA) in Visual Arts" },
  { id: "22", name: "Bachelor of Arts in Social Science" },
  { id: "23", name: "Bachelor of Business Administration (BBA)" },
  { id: "24", name: "Bachelor of Education (B.Ed.)" },
  { id: "25", name: "Bachelor of Science (B.Sc.)" },
  { id: "26", name: "Bachelor of Science in Aerospace Engineering" },
  { id: "27", name: "Bachelor of Science in Artificial Intelligence" },
  { id: "28", name: "Bachelor of Science in Astronomy (B.S.A.)" },
  { id: "29", name: "Bachelor of Science in Athletic Training" },
  { id: "30", name: "Bachelor of Science in Biology (B.S.B.)" },
  { id: "31", name: "Bachelor of Science in Biomedical Engineering" },
  { id: "32", name: "Bachelor of Science in Chemical Engineering" },
  { id: "33", name: "Bachelor of Science in Chemistry (B.S.C.)" },
  { id: "34", name: "Bachelor of Science in Civil Engineering" },
  { id: "35", name: "Bachelor of Science in Computer Engineering" },
  { id: "36", name: "Bachelor of Science in Computer Science" },
  { id: "37", name: "Bachelor of Science in Computer Science (B.S.C.S.)" },
  { id: "38", name: "Bachelor of Science in Cyber Security" },
  { id: "39", name: "Bachelor of Science in Data Science" },
  { id: "40", name: "Bachelor of Science in Electrical Engineering" },
  { id: "41", name: "Bachelor of Science in Engineering (B.S.E.)" },
  { id: "42", name: "Bachelor of Science in Environmental Engineering" },
  { id: "43", name: "Bachelor of Science in Environmental Science (B.S.E.S.)" },
  { id: "44", name: "Bachelor of Science in Exercise Science" },
  { id: "45", name: "Bachelor of Science in Health Information Management" },
  { id: "46", name: "Bachelor of Science in Health Promotion" },
  { id: "47", name: "Bachelor of Science in Health Science" },
  { id: "48", name: "Bachelor of Science in Industrial Engineering" },
  { id: "49", name: "Bachelor of Science in Information Systems" },
  { id: "50", name: "Bachelor of Science in Information Technology" },
  {
    id: "51",
    name: "Bachelor of Science in Information Technology (B.S.I.T.)",
  },
  { id: "52", name: "Bachelor of Science in Marine Engineering" },
  { id: "53", name: "Bachelor of Science in Mathematics (B.S.M.)" },
  { id: "54", name: "Bachelor of Science in Mechanical Engineering" },
  { id: "55", name: "Bachelor of Science in Networking and Security" },
  { id: "56", name: "Bachelor of Science in Nuclear Engineering" },
  { id: "57", name: "Bachelor of Science in Nursing" },
  { id: "58", name: "Bachelor of Science in Nursing (B.S.N.)" },
  { id: "59", name: "Bachelor of Science in Occupational Therapy" },
  { id: "60", name: "Bachelor of Science in Physics" },
  { id: "61", name: "Bachelor of Science in Physics (B.S.P.)" },
  { id: "62", name: "Bachelor of Science in Social Science" },
  { id: "63", name: "Bachelor of Science in Software Engineering" },
  { id: "64", name: "Bachelor of Science in Web Development" },
  { id: "65", name: "Certificate in Legal Studies" },
  { id: "66", name: "Certificate in Paralegal Studies" },
  { id: "67", name: "Doctor of Athletic Training" },
  { id: "68", name: "Doctor of Business Administration (DBA)" },
  { id: "69", name: "Doctor of Dental Medicine (DMD)" },
  { id: "70", name: "Doctor of Education (Ed.D.)" },
  { id: "71", name: "Doctor of Education in Social Science" },
  { id: "72", name: "Doctor of Health Administration" },
  { id: "73", name: "Doctor of Health Promotion" },
  { id: "74", name: "Doctor of Juridical Science (SJD)" },
  { id: "75", name: "Doctor of Medicine (MD)" },
  { id: "76", name: "Doctor of Nursing Practice" },
  { id: "77", name: "Doctor of Occupational Therapy" },
  { id: "78", name: "Doctor of Optometry (OD)" },
  { id: "79", name: "Doctor of Osteopathic Medicine (DO)" },
  { id: "80", name: "Doctor of Philosophy (Ph.D.)" },
  { id: "81", name: "Doctor of Philosophy in Business Administration (PhD)" },
  { id: "82", name: "Doctor of Philosophy in Education (Ph.D.)" },
  { id: "83", name: "Doctor of Philosophy in Health Science" },
  { id: "84", name: "Doctor of Philosophy in Law (PhD)" },
  { id: "85", name: "Doctor of Philosophy in Physics" },
  { id: "86", name: "Doctor of Philosophy in Social Science" },
  { id: "87", name: "Doctor of Physical Therapy" },
  { id: "88", name: "Doctor of Podiatric Medicine (DPM)" },
  { id: "89", name: "Doctor of Science (D.Sc.)" },
  { id: "90", name: "Doctor of Veterinary Medicine (DVM)" },
  { id: "91", name: "Educational Specialist (Ed.S.)" },
  { id: "92", name: "Juris Doctor (JD)" },
  { id: "93", name: "Master of Applied Anthropology" },
  { id: "94", name: "Master of Applied Economics" },
  { id: "95", name: "Master of Applied History" },
  { id: "96", name: "Master of Applied Political Science" },
  { id: "97", name: "Master of Applied Psychology" },
  { id: "98", name: "Master of Applied Science (M.A.Sc.)" },
  { id: "99", name: "Master of Applied Sociology" },
  { id: "100", name: "Master of Applied Statistics" },
  { id: "101", name: "Master of Arts in Curriculum and Instruction (MACI)" },
  { id: "102", name: "Master of Arts in Early Childhood Education (MAECE)" },
  { id: "103", name: "Master of Arts in Educational Administration (MAEA)" },
  { id: "104", name: "Master of Arts in Educational Leadership (MAEL)" },
  { id: "105", name: "Master of Arts in Educational Psychology (MAEP)" },
  { id: "106", name: "Master of Arts in Educational Technology (MAET)" },
  { id: "107", name: "Master of Arts in Physics" },
  { id: "108", name: "Master of Arts in Social Science" },
  { id: "109", name: "Master of Arts in Special Education (MASP)" },
  { id: "110", name: "Master of Arts in Teaching (MAT)" },
  { id: "111", name: "Master of Business Administration (MBA)" },
  { id: "112", name: "Master of Comparative Law (MCL)" },
  { id: "113", name: "Master of Conflict Resolution" },
  { id: "114", name: "Master of Education (M.Ed.)" },
  { id: "115", name: "Master of Health Administration" },
  { id: "116", name: "Master of Health Administration (MHA)" },
  { id: "117", name: "Master of International Relations" },
  { id: "118", name: "Master of Laws (LLM)" },
  { id: "119", name: "Master of Legal Studies (MLS)" },
  { id: "120", name: "Master of Nonprofit Management" },
  { id: "121", name: "Master of Professional Studies in Law (MPSL)" },
  { id: "122", name: "Master of Public Administration" },
  { id: "123", name: "Master of Public Health" },
  { id: "124", name: "Master of Public Health (MPH)" },
  { id: "125", name: "Master of Public Policy" },
  { id: "126", name: "Master of Science (M.Sc.)" },
  { id: "127", name: "Master of Science in Accounting (MSA)" },
  { id: "128", name: "Master of Science in Acoustics" },
  { id: "129", name: "Master of Science in Aerospace Engineering" },
  { id: "130", name: "Master of Science in Applied Physics" },
  { id: "131", name: "Master of Science in Artificial Intelligence" },
  { id: "132", name: "Master of Science in Astronomy" },
  { id: "133", name: "Master of Science in Astronomy (M.S.A.)" },
  { id: "134", name: "Master of Science in Astrophysics" },
  { id: "135", name: "Master of Science in Athletic Training" },
  { id: "136", name: "Master of Science in Automation Engineering" },
  { id: "137", name: "Master of Science in Automotive Engineering" },
  { id: "138", name: "Master of Science in Bioinformatics" },
  { id: "139", name: "Master of Science in Biology (M.S.B.)" },
  { id: "140", name: "Master of Science in Biomedical Engineering" },
  { id: "141", name: "Master of Science in Biomedical Sciences (MSBS)" },
  { id: "142", name: "Master of Science in Biophysics" },
  { id: "143", name: "Master of Science in Chemistry (M.S.C.)" },
  { id: "144", name: "Master of Science in Civil Engineering" },
  { id: "145", name: "Master of Science in Clinical Research (MSCR)" },
  { id: "146", name: "Master of Science in Computational Physics" },
  { id: "147", name: "Master of Science in Computer Engineering" },
  { id: "148", name: "Master of Science in Computer Science" },
  { id: "149", name: "Master of Science in Computer Science (M.S.C.S.)" },
  { id: "150", name: "Master of Science in Curriculum and Instruction (MSCI)" },
  { id: "151", name: "Master of Science in Cyber Security" },
  { id: "152", name: "Master of Science in Data Science" },
  { id: "153", name: "Master of Science in Early Childhood Education (MSECE)" },
  { id: "154", name: "Master of Science in Education (MSEd)" },
  { id: "155", name: "Master of Science in Educational Administration (MSEA)" },
  { id: "156", name: "Master of Science in Educational Leadership (MSEL)" },
  { id: "157", name: "Master of Science in Educational Psychology (MSEP)" },
  { id: "158", name: "Master of Science in Educational Technology (MSET)" },
  { id: "159", name: "Master of Science in Electrical Engineering" },
  { id: "160", name: "Master of Science in Engineering (M.S.E.)" },
  { id: "161", name: "Master of Science in Environmental Science (M.S.E.S.)" },
  { id: "162", name: "Master of Science in Exercise Physiology" },
  { id: "163", name: "Master of Science in Finance (MSF)" },
  { id: "164", name: "Master of Science in Geophysics" },
  {
    id: "165",
    name: "Master of Science in Health Care Administration (MSHCA)",
  },
  { id: "166", name: "Master of Science in Health Education" },
  { id: "167", name: "Master of Science in Health Education (MSHE)" },
  { id: "168", name: "Master of Science in Health Informatics" },
  { id: "169", name: "Master of Science in Health Informatics (MSHI)" },
  {
    id: "170",
    name: "Master of Science in Health Policy and Management (MSHPM)",
  },
  { id: "171", name: "Master of Science in Health Promotion" },
  { id: "172", name: "Master of Science in Health Psychology" },
  { id: "173", name: "Master of Science in Health Science" },
  { id: "174", name: "Master of Science in Health Services Research (MSHSR)" },
  { id: "175", name: "Master of Science in Human Resources (MSHR)" },
  { id: "176", name: "Master of Science in Industrial Engineering" },
  { id: "177", name: "Master of Science in Information Systems (MSIS)" },
  { id: "178", name: "Master of Science in Information Technology" },
  { id: "179", name: "Master of Science in Information Technology (M.S.I.T.)" },
  { id: "180", name: "Master of Science in Law (MSL)" },
  { id: "181", name: "Master of Science in Management (MSM)" },
  { id: "182", name: "Master of Science in Marketing (MSMkt)" },
  { id: "183", name: "Master of Science in Materials Science" },
  { id: "184", name: "Master of Science in Mathematics (M.S.M.)" },
  { id: "185", name: "Master of Science in Mechanical Engineering" },
  { id: "186", name: "Master of Science in Medical Education (MSME)" },
  { id: "187", name: "Master of Science in Medical Physics" },
  { id: "188", name: "Master of Science in Medical Physics (MSMP)" },
  { id: "189", name: "Master of Science in Meteorology" },
  { id: "190", name: "Master of Science in Network Engineering" },
  { id: "191", name: "Master of Science in Nuclear Physics" },
  { id: "192", name: "Master of Science in Nursing" },
  { id: "193", name: "Master of Science in Nursing (M.S.N.)" },
  { id: "194", name: "Master of Science in Nursing (MSN)" },
  { id: "195", name: "Master of Science in Nutrition" },
  { id: "196", name: "Master of Science in Occupational Therapy" },
  { id: "197", name: "Master of Science in Optics and Photonics" },
  { id: "198", name: "Master of Science in Particle Physics" },
  { id: "199", name: "Master of Science in Pharmaceutical Sciences (MSPS)" },
  {
    id: "200",
    name: "Master of Science in Physician Assistant Studies (MSPAS)",
  },
  { id: "201", name: "Master of Science in Physics" },
  { id: "202", name: "Master of Science in Physics (M.S.P.)" },
  { id: "203", name: "Master of Science in Plasma Physics" },
  { id: "204", name: "Master of Science in Quantum Mechanics" },
  { id: "205", name: "Master of Science in Robotics Engineering" },
  { id: "206", name: "Master of Science in Social Science" },
  { id: "207", name: "Master of Science in Software Engineering" },
  { id: "208", name: "Master of Science in Special Education (MSSP)" },
  { id: "209", name: "Master of Science in Speech-Language Pathology" },
  { id: "210", name: "Master of Science in Systems Engineering" },
  { id: "211", name: "Master of Science in Telecommunications Engineering" },
  { id: "212", name: "Master of Science in Theoretical Physics" },
  { id: "213", name: "Master of Social Work" },
  { id: "214", name: "Master of Urban Planning" },
];
