export default [
  "Graphic Designer",
  "UI Designer",
  "UX Designer",
  "Web Designer",
  "Visual Designer",
  "Art Director",
  "Creative Director",
  "Motion Designer",
  "Product Designer",
  "Interaction Designer",
  "Brand Designer",
  "Illustrator",
  "Animation Designer",
  "Packaging Designer",
  "User Researcher",
  "Information Architect",
  "Game Designer",
  "Digital Designer",
  "Experience Designer",
  "Multimedia Designer",
  "Print Designer",
  "Environmental Designer",
  "Industrial Designer",
  "Service Designer",
  "UI/UX Developer",
  "Marketing Designer",
  "Content Designer",
  "UI/UX Architect",
  "UI/UX Strategist",
  "UI/UX Analyst",
  "UI/UX Consultant",
];
