export default [
  "Financial Analyst",
  "Accountant",
  "Financial Manager",
  "Investment Banker",
  "Financial Advisor",
  "Risk Manager",
  "Credit Analyst",
  "Tax Consultant",
  "Treasury Analyst",
  "Auditor",
  "Budget Analyst",
  "Controller",
  "Mergers and Acquisitions Analyst",
  "Portfolio Manager",
  "Financial Planner",
  "Actuary",
  "Compliance Officer",
  "Financial Operations Manager",
  "Financial Consultant",
  "Bank Manager",
  "Insurance Underwriter",
  "Business Analyst",
  "Financial Reporting Manager",
  "Finance Director",
  "Corporate Finance Associate",
  "Investment Analyst",
  "Financial Controller",
  "Hedge Fund Manager",
  "Credit Manager",
  "Private Equity Analyst",
];
