export default [
  { id: "1", name: "Photography" },
  { id: "2", name: "Cooking" },
  { id: "3", name: "Gardening" },
  { id: "4", name: "Traveling" },
  { id: "5", name: "Painting" },
  { id: "6", name: "Writing" },
  { id: "7", name: "Reading" },
  { id: "9", name: "Playing sports" },
  { id: "10", name: "Bird watching" },
  { id: "11", name: "Hiking" },
  { id: "12", name: "Camping" },
  { id: "8", name: "Playing musical instruments" },
  { id: "13", name: "Fishing" },
  { id: "14", name: "Shopping" },
  { id: "16", name: "Collecting stamps" },
  { id: "15", name: "Collecting coins" },
  { id: "17", name: "Collecting antiques" },
  { id: "18", name: "Collecting art" },
  { id: "19", name: "Collecting books" },
  { id: "20", name: "Playing games" },
  { id: "22", name: "Watching movies" },
  { id: "23", name: "Watching TV" },
  { id: "24", name: "Going to theater" },
  { id: "25", name: "Going to concerts" },
  { id: "26", name: "Going to opera" },
  { id: "27", name: "Going to ballet" },
  { id: "28", name: "Going to circus" },
  { id: "29", name: "Going to zoo" },
];
