export default [
  "Software Engineer",
  "Web Developer",
  "Mobile App Developer",
  "Data Scientist",
  "Database Administrator",
  "Systems Analyst",
  "Network Administrator",
  "Cybersecurity Analyst",
  "AI Engineer",
  "Cloud Architect",
  "DevOps Engineer",
  "IT Project Manager",
  "UI/UX Designer",
  "Quality Assurance Engineer",
  "IT Consultant",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Data Engineer",
  "Machine Learning Engineer",
  "Embedded Systems Engineer",
  "Network Engineer",
  "Systems Administrator",
  "IT Support Specialist",
  "Technical Writer",
  "IT Trainer",
  "IT Auditor",
  "Blockchain Developer",
  "Robotics Engineer",
  "Game Developer",
  "Computer Vision Engineer",
];
