const techCompanies = [
  "Babylon Health",
  "Darktrace",
  "Revolut",
  "Deliveroo",
  "Apple",
  "Amazon",
  "Google",
  "Microsoft",
  "Facebook",
  "Monzo",
  "ARM Holdings",
  "Just Eat",
  "TransferWise",
  "Ocado",
  "Farfetch",
  "Netflix",
  "Tesla",
  "Uber",
  "Twitter",
  "Salesforce",
];

const designerCompanies = [
  "Burberry",
  "Alexander McQueen",
  "Vivienne Westwood",
  "Stella McCartney",
  "Mulberry",
  "Ralph Lauren",
  "Calvin Klein",
  "Michael Kors",
  "Tom Ford",
  "Oscar de la Renta",
  "Paul Smith",
  "Jimmy Choo",
  "Ted Baker",
  "JW Anderson",
  "Christopher Kane",
  "Marc Jacobs",
  "Kate Spade",
  "Coach",
  "DKNY",
  "Tory Burch",
];

const financeCompanies = [
  "HSBC",
  "Barclays",
  "Lloyds Banking Group",
  "Standard Chartered",
  "Prudential",
  "JPMorgan Chase",
  "Bank of America",
  "Citigroup",
  "Wells Fargo",
  "Legal & General",
  "M&G",
  "Schroders",
  "Goldman Sachs",
  "Morgan Stanley",
  "American Express",
  "Visa",
  "Mastercard",
  "Capital One",
  "Aviva",
];

export default { techCompanies, designerCompanies, financeCompanies };
